version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    assignees:
      - ganto

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
