---
repositories:
  alma:
    suffixes:
      - .drpm
      - .rpm
    upstreams:
      - https://repo.almalinux.org
  epel:
    suffixes:
      - .drpm
      - .rpm
    upstreams:
      - http://dl.fedoraproject.org/pub/epel
  centos:
    suffixes:
      - .drpm
      - .rpm
    upstreams:
      - http://mirror.centos.org/centos
  fedora:
    suffixes:
      - .drpm
      - .rpm
    # Get mirror list via:
    # `curl "https://mirrors.fedoraproject.org/metalink?repo=fedora-36&arch=x86_64"`
    upstreams:
      - https://mirror.init7.net/fedora/fedora/linux
      - https://download.fedoraproject.org/pub/fedora/linux
