---
name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # for actions/checkout to fetch code
    steps:

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 'stable'
          check-latest: true

      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

  actionlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # for actions/checkout to fetch code
      checks: write   # for reviewdog github-pr-check reporter to report findings
    steps:

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - uses: reviewdog/action-actionlint@dbe5299849118fd6f099ba563d263d770955a64a # v1

  golangci-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # for actions/checkout to fetch code
    steps:

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 'stable'
          check-latest: true

      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: latest
          args: --verbose

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # for actions/checkout to fetch code
    steps:

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 'stable'
          check-latest: true

      - run: make test
