---
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          check-latest: true

      - uses: pre-commit/action@v3.0.0

  golangci-lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4

      - uses: golangci/golangci-lint-action@v3.5.0
        with:
          version: latest
          args: --verbose

  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4

      - run: |
          export GOBIN=$HOME/go/bin
          go install github.com/kyoh86/richgo@latest

      - run: RICHGO_FORCE_COLOR=1 PATH=$HOME/go/bin/:$PATH make richtest
