---
name: Publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          check-latest: true

      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.1.0

      - name: Prepare Ko
        uses: ko-build/setup-ko@v0.9

      - name: Compute build metadata
        env:
          REVISION: ${{ github.sha }}
        run: |
          {
            echo BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
            echo REVISION="${REVISION}"
            echo VERSION="$(git describe --tags --always)"
          } >> "$GITHUB_ENV"

      - name: Build and publish container image
        env:
          SOURCE_URL: ${{ github.server_url }}/${{ github.repository }}
          ARCHS: amd64,arm64
        run: make image-build

      - name: Sign container image
        run: cosign sign --yes "$(cat image-ref.out)"
